//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment_agency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {

        public static Entities _context;

        public static Entities GetContext() 
        {
            if (_context == null) _context = new Entities();

            return _context;
        }
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Аккаунт> Аккаунт { get; set; }
        public virtual DbSet<Вакансия> Вакансия { get; set; }
        public virtual DbSet<Города> Города { get; set; }
        public virtual DbSet<Организация> Организация { get; set; }
        public virtual DbSet<Резюме> Резюме { get; set; }
        public virtual DbSet<Соискатель> Соискатель { get; set; }
        public virtual DbSet<Тип_аккаунта> Тип_аккаунта { get; set; }
    }
}
