//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment_agency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Аккаунт
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Аккаунт()
        {
            this.Организация = new HashSet<Организация>();
            this.Соискатель = new HashSet<Соискатель>();
        }
    
        public int Код_аккаунта { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Фотография { get; set; }
        public Nullable<int> Тип_аккаунта { get; set; }
    
        public virtual Тип_аккаунта Тип_аккаунта1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Организация> Организация { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Соискатель> Соискатель { get; set; }
    }
}
