//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment_agency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Организация
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Организация()
        {
            this.Вакансия = new HashSet<Вакансия>();
        }
    
        public int Код_Организации { get; set; }
        public int Код_аккаунта { get; set; }
        public string Название { get; set; }
        public string Номер_телефона { get; set; }
        public string Адрес { get; set; }
        public string Описание { get; set; }
    
        public virtual Аккаунт Аккаунт { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Вакансия> Вакансия { get; set; }
    }
}
